### ISSUE TITLE
Website is kinda broken

### ISSUE THREAD

**Issue by Paragramex** [Crazygird/Billboard#1]
I think the website is broken because when you click on any "buttons" nothing happens. I checked the console and got this error:
```js
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at menu ((index):167:9)
    at HTMLImageElement.<anonymous> ((index):184:7)
    at HTMLImageElement.dispatch (jquery-3.6.4.min.js:2:43184)
    at y.handle (jquery-3.6.4.min.js:2:41168)
```

**Comment by Crazygird** [comment]
Well, the website is still being built so expect some errors.

**Comment by bluehalooo** [comment]
we're still working on it, button functionality is a priority though.
